typography_spectrum: 0.49772
color:
  brandColors:
    - '#131e09'
    - '#a6b2bc'
    - '#737e84'
    - '#77a200'
    - '#eaf5fc'
  brandStrength: 0.3202001212630421
  lightness: 0.009763110894709826
  saturation: 0.257723739836365
  rhythmicContrast: 0.3375902194529772
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.16337
analytics:
  google: null
  facebook: null
  twitter: null
name: foster
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: hi
purpose: []
